### ISSUE TITLE
Switching between available and unavailable

### ISSUE THREAD

**Issue by schmuy** [ufodone/envisalink_new#22] opened 2023-02-14 18:23 UTC
Updated to 0.5.1 this morning.  Device is bouncing back and forth between available and unavailable every 15s or so. 

[home-assistant_2023-02-14T18-14-37.045Z.log](https://github.com/ufodone/envisalink_new/files/10735658/home-assistant_2023-02-14T18-14-37.045Z.log)

**Comment by ufodone** [comment] 2023-02-14 18:53
What version did you upgrade from?

From the logs it looks like your EVL doesn't seem to be responding to the 071 commands being issued to fetch the zone bypass state at login.   But the initial connection in the log also looks like the EVL just stopped sending data altogether as a see a handful of 610 updates but not nearly the number I'd expect.  

The next connection attempt sends all the updates as expected but it looks like maybe the restart has happened while the alarm is armed?  We know something's going on with that already due to the other issue you opened and I'm starting to wonder now whether issuing zone bypass queries while armed is generally an unreliable thing to do.

I also notice that at some point something is also issuing what looks like a series of zone bypass commands.  Is that expected based on some automations/etc. you might have?

One other note: I see you're running firmware 01.04.176.  There is a newer version available which you might consider upgrading to (I don't know if that would be related to this issue or not).  I've been running 0.5.1 on my own system with the bypass switches enabled on 01.04.182 without problem (although I haven't tried restarting while the system is armed).

**Comment by schmuy** [comment] 2023-02-14 19:18
> What version did you upgrade from?
4.1 I think.  I deleted integration, update, then restart.

>  looks like maybe the restart has happened while the alarm is armed? 
Yup.  I'm the guy that thinks lets do a major update on beta software when offsite and I have a 15min coffee break.

> I also notice that at some point something is also issuing what looks like a series of zone bypass commands. Is that expected based on some automations/etc. you might have?
I have automations which will automatically bypass a zone under various conditions.  State changing from available to unavailable might be trying to trigger those automations.

> I see you're running firmware 01.04.176. There is a newer version available...
Unfortunately I don't see any update available.   [This Changeling Link](https://forum.eyezon.com/viewtopic.php?t=5115) says "Release only for Sidekick users AND new customers with factory firmware" for everything since 176.

**Comment by ufodone** [comment] 2023-02-14 19:24
I see one exception in the log which needs a fix but it only happens once and seems to recover.  Other than that, I can't think of anything new since 0.4.1 that might introduce this issue.  

I'm guessing this is related to the zone bypass stuff when starting/restarting while armed.  I may need to prevent those commands from being issued while the alarm is in the armed state.  I'll try and have a look at that soon.

**Comment by schmuy** [comment] 2023-02-14 19:44
I have disarmed the system with the eyezon app and have had many restarts with it disarmed and I am getting the same behaviour

**Comment by ufodone** [comment] 2023-02-14 19:47
Just to rule something out... in Settings -> Devices & Services, for the envisalink_new integration, is it showing 1 device or 2?

**Comment by schmuy** [comment] 2023-02-14 20:15
Just 1 device

**Comment by schmuy** [comment] 2023-02-14 20:20
I'm having to disable the integration as it's messing with too much stuff.  Here's a log for a few min after re-enabling.  I don't know if it shows anything different than the first log.

[home-assistant_2023-02-14T20-17-32.258Z.log](https://github.com/ufodone/envisalink_new/files/10736550/home-assistant_2023-02-14T20-17-32.258Z.log)

**Comment by ufodone** [comment] 2023-02-14 21:13
My best guess at the moment is that the EVL doesn't like the quick sequence of zone bypass calls.  It appears to be getting hung up on them and stops responding.  I'll try and reproduce it later on my own system.

**Comment by ufodone** [comment] 2023-02-15 03:30
I was able to reproduce this by issuing a series of zone bypass commands in quick succession on startup like I saw in your logs.  I believe I've fixed in in 0.5.2 now.

**Comment by schmuy** [comment] 2023-02-15 04:00
That's awesome,  Thanks.

What in the logs do you see that tells you a bypass command is sent? Lines like: `Queueing command '071' data: '1*110#'`?  I can try to match that up with my entity logs.  

I'm guessing the switching between unavailable to off was triggering an automation which probably caused things to snowball.

**Comment by ufodone** [comment] 2023-02-15 04:30
Yes, the `071` commands are keypress commands and the `1*110#` means sends to partition 1 the keypresses `*110#` which toggles the bypass for zone 10.  The `1*1#` trigger the EVL to send the bypass status in a 616 message.

The `Queueing command` is when the command get issues and then there would be a `TX` line with `071` that shows it being sent to the EVL.  There would then be a `RX` back as `500071` for success or a different "500" response like `502` which indicates an error.

It executes all the command in sequence now and waits for the response from the previous command before issuing another one.  So you might see a batch of `Queueing command` messages all together but the corresponding `TX` entries would be spread out as it issues each one in sequence.

**Comment by schmuy** [comment] 2023-02-16 17:10
Updated to 5.2 and everything is looking good so far.

**Closed** 2023-02-16 17:37 UTC
