### ISSUE TITLE
HAOS Envisalink 4 Vista 128bpt Install Status

### ISSUE THREAD

**Issue by ddetton** [ufodone/envisalink_new#67] opened 2023-11-26 04:00 UTC
Only have one issue which I'll cover below.  I just wanted to report my upgrade experience.  I originally had the packaged Envisalink integration with all configuration details in the configuration.yaml.  I downloaded envisalink_new from HACS then rebooted.  I loaded the integration but it failed because it said that there was one already connected.  So I changed the yaml tag to envisalink_new but it wouldn't let me reboot because it said my yaml was invalid.  So I removed the envisalink section from my yaml and rebooted.  Now I am able to load the integration and the device with all entities are created.  I just went into each of my zones and change the entity name.  Obviously, it wasn't clear to me how the upgrade was supposed to work.  Ideally, it would have pulled in the zone names from the original yaml but I must have did something wrong.

One issue I am seeing is when I open a single door and close it, the button card for that sensor activates when the door is open and deactivates when I close it.  But if I open a door without closing it, then open another door, feedback for the second door is delayed several seconds before it activates.  Then if I close the first door while leaving the second door open, feedback for the first door stays activated until I close the second door.  Once the second door is closed, both sensors are deactivated.   I am using mushroom entity cards for the sensors and they are all inside a grid card.  Have not tried this with packaged envisalink component.  Opening a separate issue with just this.

My motivation for doing this was so that I could assign sensors to areas and I can do that now so we're all good.  Let me know if you have any questions or answers.  Thanks for putting this together.  Much appreciated!

**Comment by ufodone** [comment] 2024-02-11 18:49
Closing this as I believe the issue is the same as discussed in #70

**Closed by ufodone** 2024-02-11 18:49 UTC
