### ISSUE TITLE
Restart home assistant while Armed Away creates mismatch between panel and keypad

### ISSUE THREAD

**Issue by schmuy** [ufodone/envisalink_new#15] opened 2023-02-07 22:11 UTC
Just noticed the issue where if HA is restarted while Armed Away, the panel and keypad don't report the same (keypad reports Arm Stay)

**Comment by ufodone** [comment] 2023-02-08 04:35
Can you remind me what type of panel you have?  DSC or Honeywell?

Are you saying that the physical keypad reports different than in HA or that the keypad sensor in HA reports differently than the alarm control entity?

Any chance you could get debug logs reproducing the issue?

**Comment by schmuy** [comment] 2023-02-08 04:55
DSC panel.  I don't know what the physical keypad was doing, I just noticed the problem with the keypad sensor.  Screenshot attached showing restart, disarm, re-arm, restart, disarm, re-arm. logs link attached (too long to post here) starting after the second restart including disarm, and re-arm.

<img width="1418" alt="Screenshot 2023-02-07 at 20 54 20" src="https://user-images.githubusercontent.com/93694290/217437020-443faf86-7882-446b-b7cc-2c56ed665a2a.png">


[https://pastebin.com/BZCSSq3g](url)

**Comment by ufodone** [comment] 2023-02-08 05:15
The link to the log doesn't appear to be correct.  You should be able to just drag-and-drop the log file itself to this issue and GitHub will attach it as a file/link automatically (rather than pasting the log contents here as a comment).

**Comment by schmuy** [comment] 2023-02-08 05:39
Yup
[home-assistant_2023-02-08T04-38-00.325Z.log](https://github.com/ufodone/envisalink_new/files/10682116/home-assistant_2023-02-08T04-38-00.325Z.log)

**Comment by rct** [comment] 2023-02-08 19:43
FYI, I believe I've seen this behavior with the existing integration on either 2022.12 or 2023.1

**Comment by ufodone** [comment] 2023-02-09 02:39
Okay, I see what's wrong but interestingly if I were to fix it, then both the panel and the keypad would report "Arm Stay".

Oddly the EVL is actually sending a partition update indicating that the alarm is in the "Arm Stay" mode.  It comes right after a couple of keypad LED state updates which are showing the bypass LED going on and off - which I suspect is due to the command issued at startup to query the zone bypass state.  

I wonder if this spurious updating indicating "Arm Away" is somehow triggered by that.  Are you able to try disabling the zone bypass switches and see if that makes the problem go away?

**Comment by schmuy** [comment] 2023-02-11 18:20
I haven't yet been able to take a look further into this..hectic week.  I'll try to take a look soon.

It does seem similar to a similar issue I reported about a month ago in the beta envisalink that had bypass switches.

**Comment by ufodone** [comment] 2023-02-12 00:13
No problem.  Same here.  I finally got through a bit of a backlog of changes I wanted to get done for this integration so I'll also see if I can reproduce it.

**Comment by ufodone** [comment] 2023-02-15 03:32
I tried reproducing this on my own system but didn't see the same behaviour as was in your log file.  

When you get a chance can you try and reproduce with the latest release and if it's still happening, disable the zone bypass switches and see if it still happens.  Thanks!

**Comment by ufodone** [comment] 2023-03-04 17:58
@schmuy I'd forgotten I had made a fix for this over on the `dscalarm` version.  I've pulled that change over now.  Please let me know if it addresses your issue.

**Comment by schmuy** [comment] 2023-03-29 20:33
Finally able to check on this.  After a restart it is still coming up with panel "arm away" and keypad sensor "arm stay"

**Comment by ufodone** [comment] 2023-03-31 03:42
A few things from the logs:

1. Fix change I pulled over from the dscalarm integration didn't work as expected with this new version so it's not actually suppressing the bypass zone commands while the alarm is armed.  I can look at fixing that.
2. It's actually timing out the above command on the initial start, disconnecting, and then reconnecting 30 seconds later.  Fixing the first item should eliminate this but it's a bit interesting nevertheless.
3. It's actually the EVL that's getting mixed up with the `away` and `stay` state.  When HA initially connects, the EVL sends  a couple 652 updates for partition 1 indicating a mode of `stay` (1).   56 seconds later is send another 652 update for partition 1 indicating a mode of `away` (0).

That last one is what's causing the mismatch between the panel and keypad.  I should be able to fix the mismatch fairly easily but it will only reflect what the EVL is say so you'd see armed stay for the first minute or so and then it would switch to armed away.  

It's possible that the zone bypass dumps while the alarm is armed (item 1 above) are causing the EVL to behave oddly.  An easy way to confirm this would be to just disable the zone bypass switches temporarily and see if the same behaviour exists.

**Comment by ufodone** [comment] 2023-05-06 03:16
@schmuy I've pushed a new release which some changes which I hope will fix this issue.  You shouldn't' see a mismatch in state between the panel and keypad anymore but you may still see the wrong state for a while because HA will just be reflecting what the EVL is telling it - which could be incorrect based on the logs you provided.

I've also made some changes to how the zone bypass switches work which I'm hoping may prevent the EVL from sending incorrect state.

**Comment by ufodone** [comment] 2023-06-19 04:08
I believe this should be fixed now with the fixes I also made for #38.  The changes are included in [v0.6.7](https://github.com/ufodone/envisalink_new/releases/tag/v0.6.7).

**Closed by ufodone** 2023-06-19 04:08 UTC
